### ISSUE TITLE
Solicita componente de teste

### ISSUE THREAD

**Issue by eduardo-inativo** [libs-scripts-mep/utils-pvi#1]
Esse método não trata o retorno do prompt como null, ver imagens

![image](https://user-images.githubusercontent.com/80358218/198580164-b952488a-6252-434a-8658-634fa5bf429e.png)
![image](https://user-images.githubusercontent.com/80358218/198580182-7b202e06-d7c9-4811-b436-728a04222839.png)

Minha sugestão: 

![image](https://user-images.githubusercontent.com/80358218/198580227-c08e2567-e3cd-40a8-9ecf-05672993666c.png)

**Comment by thiagosantosinova** [comment]
@eduardo-rezzadori  Bug resolvido!
